// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClinicToggleController from "./clinic_toggle_controller"
application.register("clinic-toggle", ClinicToggleController)

import ConnectionSubscriptionController from "./connection_subscription_controller"
application.register("connection-subscription", ConnectionSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import ShowMapController from "./show_map_controller"
application.register("show-map", ShowMapController)

import SymptomController from "./symptom_controller"
application.register("symptom", SymptomController)
